name: 🚀 Deploy Angular App to Hostinger (manage.purehomewaters.com)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      - name: Build Angular App
        run: npm run build -- --configuration production --base-href /manage/

      - name: Add .htaccess for Angular Routing
        run: |
          echo '<IfModule mod_rewrite.c>
          RewriteEngine On
          RewriteBase /manage/
          RewriteRule ^index\.html$ - [L]
          RewriteCond %{REQUEST_FILENAME} !-f
          RewriteCond %{REQUEST_FILENAME} !-d
          RewriteRule . /manage/index.html [L]
          </IfModule>
          Options -Indexes' > dist/*/.htaccess

      - name: Deploy via FTP to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.3
        with:
          server: ${{ secrets.HOSTINGER_FTP_HOST }}
          username: ${{ secrets.HOSTINGER_FTP_USERNAME }}
          password: ${{ secrets.HOSTINGER_FTP_PASSWORD }}
          local-dir: "dist/phw-manage-ui/browser"
          server-dir: ${{ secrets.HOSTINGER_FTP_PATH }}
          dangerous-clean-slate: true
